### ISSUE TITLE
Distance limit shouldn't be fixed

### ISSUE THREAD

**Issue by Baughn** [justarandomgeek/factorio-pushbutton#5]
As in https://github.com/justarandomgeek/factorio-pushbutton/blob/master/control.lua#L21

Currently you're using a fixed distance limit that (presumably) was chosen to be equal to the standard interaction range limit from vanilla. However, there are mods like https://mods.factorio.com/mods/Mooncat/long-reach-research which change that limit.

Ideally, you'd use the actual (post-modification) range limit as set by those mods, as otherwise the button *appears* to be in range (the cursor goes yellow), and it can be toggled via its UI, but the hotkey doesn't work.

**Comment by justarandomgeek** [comment]
It was actually chosen slightly *longer* than the default reach, in order to make my keyboard all reachable at once. I'll make it a setting to use adjustable custom or vanilla reach.

**Comment by justarandomgeek** [comment]
This is fixed for the 0.17 update
